### ISSUE TITLE
Internal attributes

### ISSUE THREAD

**Issue by paulo-coutinho** [readium/r2-navigator-kotlin#203]
Hi,

Im trying migrate to the readium2 version 2.0.0 and need some help.

In my case i cant use directly "EpubReaderFragment" because my fragment inherit from our own generic reader fragment that has lot of methods for other readers.

So i need "rewrite" the reader fragment with my logic.

The problem is that some properties is "internal" and not "open" or "public", so i get errors like this:

![image](https://user-images.githubusercontent.com/395096/116609857-3f7fb300-a90b-11eb-9cb5-68ecc4a69e65.png)

![image](https://user-images.githubusercontent.com/395096/116610198-a2714a00-a90b-11eb-8c33-25961714273a.png)

There is anyway to change in the project the internal things to a "more public" access?

Thanks.

**Comment by qnga** [comment]
Hello,
`EpubReaderFragment` is in the test app. Did you mean `EpubNavigatorFragment`? I think you can embed it into your own fragment, as we do in the test app. Otherwise, it should still be possible to use `R2EpubActivity` with the 2.0.0 version (it is even required if you want to benefit from all features). Making implementation details public is not really an option.

**Comment by paulo-coutinho** [comment]
Ok.

I have abandoned my old implementation and im trying replicate the testapp solution.

I have implemented this method:

![image](https://user-images.githubusercontent.com/395096/116623977-7ced3c00-a91d-11eb-9f56-8927d8dbd5de.png)

But im receiving this error:

```
androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.readium.r2.navigator.epub.EpubNavigatorFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
        at androidx.fragment.app.FragmentTransaction.createFragment(FragmentTransaction.java:150)
        at androidx.fragment.app.FragmentTransaction.add(FragmentTransaction.java:213)
        at br.com.ubook.ubookapp.ui.fragment.ReaderReadium2Fragment.onCreateView(ReaderReadium2Fragment.kt:77)
```

Main error:

```
Unable to instantiate fragment org.readium.r2.navigator.epub.EpubNavigatorFragment: could not find Fragment constructor
```

Can you help me?

**Comment by paulo-coutinho** [comment]
Hi,

I see here that left:

```
childFragmentManager.fragmentFactory = EpubNavigatorFragment.createFactory [...]
```

Im continuing and will post results here.

**Comment by paulo-coutinho** [comment]
Hi,

After copy the code form test app it finally run, get epub metadata and first html to render. But it is showing error page on webview:

![device-2021-04-29-201717](https://user-images.githubusercontent.com/395096/116629588-ebcf9280-a927-11eb-9009-4924530d1ff3.png)

Do you know what can be wrong?

**Comment by mickael-menu** [comment]
Like @qnga mentioned, we don't want to open up internals because it would tie our public API to a particular implementation.

The best way to integrate the Readium navigator fragments is to treat them as a black box and build your UI around it. If you find that some things are not possible this way, you can open another dedicated issue with more specifics and we can talk about it.

---

Regarding your last issue it looks like you didn't set up the server properly, since the WebView is loading a `file://` URL. EPUB publications need to be added to a local HTTP server to be rendered.

1. In the test app, the server is created here: https://github.com/readium/r2-testapp-kotlin/blob/7ffd1b8b8e7d58b934ad0f8589689390bf42fe45/r2-testapp/src/main/java/org/readium/r2/testapp/library/LibraryActivity.kt#L123-L128

2. And started here: https://github.com/readium/r2-testapp-kotlin/blob/7ffd1b8b8e7d58b934ad0f8589689390bf42fe45/r2-testapp/src/main/java/org/readium/r2/testapp/library/LibraryActivity.kt#L283

3. When opening a publication, it is added to the server here: https://github.com/readium/r2-testapp-kotlin/blob/7ffd1b8b8e7d58b934ad0f8589689390bf42fe45/r2-testapp/src/main/java/org/readium/r2/testapp/library/LibraryActivity.kt#L610-L613

4. This returns an URL (the base URL on the server) that you will need to provide to the EPUB navigator fragment, this is done with a ReaderContract in the test app: https://github.com/readium/r2-testapp-kotlin/blob/0f33b47d6f3a8a891753664b5286693fef1a83d5/r2-testapp/src/main/java/org/readium/r2/testapp/library/LibraryActivity.kt#L594-L604

**Comment by paulo-coutinho** [comment]
Hi,

I already do it in my code:

```
override fun createAll(view: View) {
    super.createAll(view)

    UIUtil.setActivityAsFullScreen(activity)

    streamer = Streamer(requireContext())

    val s = ServerSocket(if (BuildConfig.DEBUG) 8080 else 0)
    s.localPort
    s.close()

    localPort = s.localPort
    server = Server(localPort, br.com.ubook.ubookapp.app.Application.instance)

    launch {
        loadPublication()
    }
}

private suspend fun loadPublication() {
    val publicationPath = EnvironmentHelper.getEpubDownloadFilePath(product.catalogId, false)
    val asset = FileAsset(File(publicationPath))
    val navigatorFragmentTag = getString(R.string.epub_navigator_tag)

    streamer.open(asset, allowUserInteraction = true, sender = this)
        .onFailure {
            //
        }
        .onSuccess { publication ->
            if (publication.isRestricted) {
                publication.protectionError?.let { error ->
                    //
                }
            } else {
                startServer()

                this@ReaderReadium2Fragment.publication = publication

                val baseUrl = prepareToServe(publication, asset)

                childFragmentManager.fragmentFactory = EpubNavigatorFragment.createFactory(
                    publication,
                    baseUrl!!.file,
                    null,
                    this@ReaderReadium2Fragment
                )

                childFragmentManager.commitNow {
                    add(
                        R.id.fragment_reader_container,
                        EpubNavigatorFragment::class.java,
                        Bundle(),
                        navigatorFragmentTag
                    )
                }

                navigator =
                    childFragmentManager.findFragmentByTag(navigatorFragmentTag) as Navigator

                navigatorFragment = navigator as EpubNavigatorFragment

                // This is a hack to draw the right background color on top and bottom blank spaces
                navigatorFragment.lifecycleScope.launchWhenStarted {
                    //val appearancePref = activity.preferences.getInt(APPEARANCE_REF, 0)
                    val appearancePref = 0
                    val backgroundsColors = mutableListOf("#ffffff", "#faf4e8", "#000000")
                    navigatorFragment.resourcePager.setBackgroundColor(
                        Color.parseColor(
                            backgroundsColors[appearancePref]
                        )
                    )
                }
            }
        }
}

private fun prepareToServe(publication: Publication, asset: PublicationAsset): URL? {
    return server.addPublication(publication, null)
}

override fun onGetArguments(arguments: Bundle) {
    super.onGetArguments(arguments)

    product = arguments.getParcelable(EXTRA_PARAM_PRODUCT)!!

    AppEvents.onReadProduct(
        product.catalogId,
        product.catalogType,
        product.title
    )
}

private fun startServer() {
    if (!server.isAlive) {
        try {
            server.start()
        } catch (e: IOException) {
            // do nothing
        }

        if (server.isAlive) {
            isServerStarted = true
        }
    }
}

override fun stopServer() {
    super.stopServer()

    if (server.isAlive) {
        server.stop()
        isServerStarted = false
    }
}
```

I have debugged testapp and my app and the objects appear be the same. The URL is returned correctly in "prepareToServe" method.

**Comment by paulo-coutinho** [comment]
I solved the problem. Is the baseUrl param. Im passing the file and not the url. Changed from:

```
baseUrl.file,
```

to:

```
baseUrl.toString(),
```

Thanks.
